# Generated by Django 5.1.4 on 2026-01-01 15:44

from django.db import migrations, models


def migrate_roles_to_designations(apps, schema_editor):
    """Convert old roles to new designations"""
    Employee = apps.get_model('org', 'Employee')
    
    # Mapping from old roles to new designations
    role_mapping = {
        'ADMIN': 'HR_MANAGER',
        'MANAGER': 'SALES_MANAGER',
        'TEAM_LEAD': 'AGENT_MANAGER',
        'EMPLOYEE': 'AGENT',
    }
    
    for employee in Employee.objects.all():
        old_role = employee.role
        if old_role in role_mapping:
            employee.role = role_mapping[old_role]
            employee.save(update_fields=['role'])


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert new designations back to old roles"""
    Employee = apps.get_model('org', 'Employee')
    
    # Reverse mapping
    reverse_mapping = {
        'HR_MANAGER': 'ADMIN',
        'HR_EXECUTIVE': 'ADMIN',
        'SALES_MANAGER': 'MANAGER',
        'SENIOR_SALES_MANAGER': 'MANAGER',
        'ASSISTANT_SALES_MANAGER': 'MANAGER',
        'AGENT_RELATIONSHIP_MANAGER': 'MANAGER',
        'ASSISTANT_GENERAL_MANAGER': 'MANAGER',
        'IT_MANAGER': 'MANAGER',
        'AGENT_MANAGER': 'TEAM_LEAD',
        'AGENT': 'EMPLOYEE',
        'SALES_EXECUTIVE': 'EMPLOYEE',
        'SENIOR_RETAINER': 'EMPLOYEE',
        'TELE_CALLER': 'EMPLOYEE',
        'TRAINER': 'EMPLOYEE',
        'IT_EXECUTIVE': 'EMPLOYEE',
        'IT_GRAPHIC_DESIGNER': 'EMPLOYEE',
    }
    
    for employee in Employee.objects.all():
        new_role = employee.role
        if new_role in reverse_mapping:
            employee.role = reverse_mapping[new_role]
            employee.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        # First, change the field to allow the new values
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SENIOR_SALES_MANAGER', 'Senior Sales Manager'), ('SALES_MANAGER', 'Sales Manager'), ('ASSISTANT_SALES_MANAGER', 'Assistant Sales Manager'), ('SALES_EXECUTIVE', 'Sales Executive'), ('AGENT_RELATIONSHIP_MANAGER', 'Agent Relationship Manager'), ('AGENT_MANAGER', 'Agent Manager'), ('AGENT', 'Agent'), ('HR_MANAGER', 'HR Manager'), ('HR_EXECUTIVE', 'HR Executive'), ('ASSISTANT_GENERAL_MANAGER', 'Assistant General Manager'), ('SENIOR_RETAINER', 'Senior Retainer'), ('TELE_CALLER', 'Tele Caller'), ('TRAINER', 'Trainer'), ('IT_MANAGER', 'IT Manager'), ('IT_EXECUTIVE', 'IT Executive'), ('IT_GRAPHIC_DESIGNER', 'IT Graphic Designer'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('TEAM_LEAD', 'Team Lead'), ('EMPLOYEE', 'Employee')], default='AGENT', max_length=30),
        ),
        # Then migrate the data
        migrations.RunPython(migrate_roles_to_designations, reverse_migration),
        # Finally, remove the old choices
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SENIOR_SALES_MANAGER', 'Senior Sales Manager'), ('SALES_MANAGER', 'Sales Manager'), ('ASSISTANT_SALES_MANAGER', 'Assistant Sales Manager'), ('SALES_EXECUTIVE', 'Sales Executive'), ('AGENT_RELATIONSHIP_MANAGER', 'Agent Relationship Manager'), ('AGENT_MANAGER', 'Agent Manager'), ('AGENT', 'Agent'), ('HR_MANAGER', 'HR Manager'), ('HR_EXECUTIVE', 'HR Executive'), ('ASSISTANT_GENERAL_MANAGER', 'Assistant General Manager'), ('SENIOR_RETAINER', 'Senior Retainer'), ('TELE_CALLER', 'Tele Caller'), ('TRAINER', 'Trainer'), ('IT_MANAGER', 'IT Manager'), ('IT_EXECUTIVE', 'IT Executive'), ('IT_GRAPHIC_DESIGNER', 'IT Graphic Designer')], default='AGENT', max_length=30),
        ),
    ]
