# Generated by Django 5.1.4 on 2026-01-03 07:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_update_roles_to_designations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('tasks_completed', models.TextField(help_text='What tasks did you complete today?')),
                ('challenges', models.TextField(blank=True, help_text='Any challenges or blockers faced?')),
                ('next_day_plan', models.TextField(blank=True, help_text='What do you plan to work on tomorrow?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='org.employee')),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-report_date', 'employee'],
                'unique_together': {('employee', 'report_date')},
            },
        ),
    ]
