# Generated by Django 5.1.4 on 2026-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Joining date (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='today_hiring',
            field=models.IntegerField(default=0, help_text='Number of people hired today'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_hiring',
            field=models.IntegerField(default=0, help_text='Total hiring count'),
        ),
    ]
