# Generated by Django 5.1.4 on 2026-01-05 14:12

import django.db.models.deletion
from django.db import migrations, models


def migrate_old_roles(apps, schema_editor):
    """Convert old role names to new simplified role names"""
    Employee = apps.get_model('org', 'Employee')
    
    role_mapping = {
        'ASSISTANT_SALES_MANAGER': 'ASSISTANT_MANAGER',
        'AGENT_RELATIONSHIP_MANAGER': 'RELATIONSHIP_MANAGER',
        # Keep these as is (they already exist)
        'SALES_MANAGER': 'SALES_MANAGER',
        'AGENT': 'AGENT',
        'HR_MANAGER': 'HR_MANAGER',
        'HR_EXECUTIVE': 'HR_EXECUTIVE',
    }
    
    for old_role, new_role in role_mapping.items():
        Employee.objects.filter(role=old_role).update(role=new_role)
    
    # Delete employees with roles that are being completely removed
    removed_roles = [
        'SENIOR_SALES_MANAGER',
        'SALES_EXECUTIVE',
        'AGENT_MANAGER',
        'ASSISTANT_GENERAL_MANAGER',
        'SENIOR_RETAINER',
        'TELE_CALLER',
        'TRAINER',
        'IT_MANAGER',
        'IT_EXECUTIVE',
        'IT_GRAPHIC_DESIGNER',
    ]
    
    # Instead of deleting, convert them to AGENT (safest option)
    for role in removed_roles:
        Employee.objects.filter(role=role).update(role='AGENT')


def reverse_migration(apps, schema_editor):
    """Reverse is not fully possible, but we can try to restore some mappings"""
    Employee = apps.get_model('org', 'Employee')
    
    # Just reverse the simple mappings
    Employee.objects.filter(role='ASSISTANT_MANAGER').update(role='ASSISTANT_SALES_MANAGER')
    Employee.objects.filter(role='RELATIONSHIP_MANAGER').update(role='AGENT_RELATIONSHIP_MANAGER')


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_dailyreport_joining_date_dailyreport_sales_and_more'),
    ]

    operations = [
        # First run the data migration
        migrations.RunPython(migrate_old_roles, reverse_migration),
        
        # Then alter the field to only allow new choices
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(
                choices=[
                    ('SALES_MANAGER', 'Sales Manager'),
                    ('ASSISTANT_MANAGER', 'Assistant Manager'),
                    ('RELATIONSHIP_MANAGER', 'Relationship Manager'),
                    ('AGENT', 'Agent'),
                    ('HR_MANAGER', 'HR Manager'),
                    ('HR_EXECUTIVE', 'HR Executive')
                ],
                default='AGENT',
                max_length=30
            ),
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('designation_display', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('annual_salary', models.CharField(max_length=50)),
                ('salary_in_words', models.CharField(max_length=200)),
                ('joining_date', models.CharField(max_length=50)),
                ('offer_date', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('team_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='offer_letters/')),
                ('download_token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offer_letters', to='org.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_offer_letters', to='org.employee')),
            ],
            options={
                'verbose_name': 'Offer Letter',
                'verbose_name_plural': 'Offer Letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
